### ISSUE TITLE
「Beverly」モデルパックのバグ

### ISSUE THREAD

**Issue by erer00gg** [SistrScarlet/LittleMaidModelLoader-Fabric#1]
1.17.1Fabricの「Beverly」モデルは、障害物に遭遇すると姿勢を変える能力を失います。
このバグが修正されることを願っています。
1.17.1
![2021-10-23_09 04 25](https://user-images.githubusercontent.com/58005561/138535267-b0e14e74-8b47-41dd-b26e-fb4c175bd94b.png)
1.12.2
![2021-10-23_09 11 47](https://user-images.githubusercontent.com/58005561/138535281-48cada49-8a53-40de-9918-bec6a4a151a5.png)

MOD:
LMRB-Fa-Arc-1.17.1-3.0.3
LMML-Fa-Arc-1.17.1-3.0.9
littleMaidMob-Elsa_Chloe_Beverly-1.0

**Comment by SistrScarlet** [comment]
直しました。
ご報告ありがとうございました。
