### ISSUE TITLE
「リトルメイド」がマグマや火で焼かれると、声にバグが発生します。

### ISSUE THREAD

**Issue by erer00gg** [SistrScarlet/LittleMaidModelLoader-Fabric#2]
ボイスパックをロードしたときに、「リトルメイド」がマグマや火で焼かれると、音声バグが発生します。
使用したボイスパック：amitaro_u

https://user-images.githubusercontent.com/58005561/138573623-c88383f3-3525-4553-9fd4-cf51885583b7.mp4

**Comment by SistrScarlet** [comment]
こちらはLMRB側の不具合ですね。
LMRB 1.16.5 2.0.4と、LMRB 1.17.1 3.0.4にて修正いたしました。
ご報告ありがとうございました。
