### ISSUE TITLE
「littleforces」スキンパックの読み込みの問題

### ISSUE THREAD

**Issue by erer00gg** [SistrScarlet/LittleMaidModelLoader-Fabric#3]
「littleforces」スキンパックのアーマーモデルはLMRBのごく一部しかロードできず、さまざまなタイプのアーマーモデルはゲームに表示されません。この問題が修正されることを願っています。
![2021-10-24_13 14 21](https://user-images.githubusercontent.com/58005561/138580605-934c8103-e6da-4764-9ed9-a1d02d140983.png)
ZIPファイルの内容には、ゲーム内の非常に少数のアーマーモデルしか表示できません。
![20211024132645824](https://user-images.githubusercontent.com/58005561/138580776-9926c604-5c22-4fac-a8ce-f374f4313f8d.jpg)

**Comment by SistrScarlet** [comment]
LMML-1.16.5-2.0.9 LMML-1.17.1-3.0.11にて修正しました。

以前の仕様では、pngの入っているフォルダの名前を、テクスチャ名と認識していました。
その結果、テクスチャ名が同じになってしまい、上書きして読み込んでいました。

今回の更新で、"littleMaid"フォルダ以下をテクスチャ名と認識するように変更したので、この問題は修正されています。
