### ISSUE TITLE
LMRB 1.16.5-2.0.4 1.17.1-3.0.4には、メイドの死によって引き起こされた音声バグがあるようです

### ISSUE THREAD

**Issue by erer00gg** [SistrScarlet/LittleMaidModelLoader-Fabric#4]
#2 
以前のバージョンと同じバグで、メイドは死後も「se_hurt_nodamege」の声を頻繁に繰り返します。
このバグはまだ存在しているようですが、何が起こっているのでしょうか？
mods：
architectury-1.24.35-fabric
fabric-api-0.40.6+1.16
LMML-Fa-Arc-1.16.5-2.0.8
LMRB-Fa-Arc-1.16.5-2.0.4

voice pack：
littlemaid_voice_amitaro_u

https://user-images.githubusercontent.com/58005561/138647432-0d018bf9-59ca-42b3-b7e3-43e9c95909ce.mp4

**Comment by SistrScarlet** [comment]
LMRB-1.16.5-2.0.5 LMRB-1.17.1-3.0.5にて修正しました。
コードにミスがありました。
今度こそ修正できているはずです。
