### ISSUE TITLE
野生のメイドが雇われた後のメイドのアーマーモデルの問題

### ISSUE THREAD

**Issue by erer00gg** [SistrScarlet/LittleMaidModelLoader-Fabric#5]
スポーンエッグによってスポーンされたメイドまたはワイルドメイドの場合、メイドが雇われた後のデフォルトのアーマーは「additional」アーマーモデルです。「Beverly」のようなモデルバッグは変に見えますが、深刻なバグではありません。修正できれば素晴らしいと思います。

https://user-images.githubusercontent.com/58005561/138852967-daa9ffef-67ac-411b-8e43-c114f61be0c8.mp4

**Comment by SistrScarlet** [comment]
返信を忘れていました、遅れてすみません。
LMRB側のバグです。
いつのバージョンかは忘れましたが、現在は修正してあります。
